party/models.py
from application import db
from user.models import User 

class Party(db.Document):
    name = db.StringField(required=True)
    place = db.StringField(required=True)
    location = db.PointField(required=True)
    start_datetime = db.DateTimeField(required=True)
    end_datetime = db.DateTimeField(required=True)
    party_photo = db.StringField()
    description = db.StringField(min_length=50,required=True)
    host = db.ObjectIdField(required=True)
    cancel = db.BooleanField(default=False)
    attendees = db.ListField(db.ReferenceField(User))

party/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,validators,DateTimeField,FloatField
from wtforms.widgets import TextArea
from flask_wtf.file import FileField,FileAllowed

class BasicPartyForm(FlaskForm):
    name = StringField('Party Name', validators=[validators.DataRequired(), validators.Length(min=2,max=80)])
    gplace = StringField('Google Place API')
    place = StringField('Place', validators=[validators.DataRequired()], widget=TextArea())
    lng = FloatField('Longitude', validators=[validators.Optional()])
    lat = FloatField('Latitude', validators=[validators.Optional()])
    start_datetime = DateTimeField('Start Time',
                                 validators=[validators.DataRequired()],
                                 format='%Y-%m-%d %H:%M')
    end_datetime = DateTimeField('End Time',
                                 validators=[validators.DataRequired()],
                                 format='%Y-%m-%d %H:%M')                             
    description = StringField('Description', widget=TextArea(), validators=[validators.Length(min=50)])

class EditPartyForm(BasicPartyForm):
    photo = FileField('Party photo',
                     validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'],
                                             'Only allow .jpg .png and .gif files')])    

class CancelPartyForm(FlaskForm):
    confirm = StringField('Are you sure you want to cancel this party? (say yes)',
                         validators=[validators.DataRequired()])

party/views.py
from flask import Blueprint,render_template,request,session,redirect,url_for,abort
import bson

from party.forms import BasicPartyForm,EditPartyForm,CancelPartyForm
from user.decorators import login_required
from party.models import Party
from user.models import User 
from utilities.storage import upload_image_file

party_page =Blueprint('party_page',__name__)

@party_page.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = BasicPartyForm()
    error = None
    if request.method == 'POST' and form.validate():
        if form.end_datetime.data < form.start_datetime.data:
            error = "A party must end after it starts!"
        if not error:
            user = User.objects.filter(email=session.get('email')).first()

            party = Party(
                 name=form.name.data,
                 place=form.place.data,
                 location=[form.lng.data,form.lat.data],
                 start_datetime=form.start_datetime.data,
                 end_datetime=form.end_datetime.data,
                 description=form.description.data,
                 host=user.id,
                 attendees=[user]
            )
            party.save()
            #return '{} created.'.format(party.name)
            return redirect(url_for('party_page.edit', id=party.id))
    return render_template('party/create.html', form=form, error=error)

@party_page.route('/<id>/edit',methods=['GET','POST'])
@login_required
def edit(id):
    try :
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)

    user = User.objects.filter(email=session.get('email')).first()

    if party and party.host == user.id:
        error = None
        message = None 
        form = EditPartyForm(obj=party)
        if request.method == 'POST' and form.validate():
            if form.end_datetime.data < form.start_datetime.data:
                error = 'A party must end after it starts!'
            if not error: 
                form.populate_obj(party)
                if form.lng.data and form.lat.data: 
                    party.location = [form.lng.data,form.lat.data]
                image_url = upload_image_file(request.files.get('photo'),'party_photo/',str(party.id))
                if image_url:
                    party.party_photo = image_url
                party.save()
                message = 'Party updated'
        return render_template('party/edit.html', form=form, error=error, message=message, party=party)
    else:
        abort(404)

@party_page.route('/testphoto')
def testphoto():
    return render_template('party/testphoto.html')
'''
@app.route('/')
def hello_world():
    return 'Hello, World!'
'''

@party_page.route('/<id>/cancel', methods=['GET','POST'])
@login_required
def cancel(id):
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
        
    user = User.objects.filter(email=session.get('email')).first()
    
    if party and party.host == user.id and party.cancel == False:
        error = None
        form = CancelPartyForm()
        if request.method == 'POST' and form.validate():
            if form.confirm.data == 'yes':
                party.cancel = True
                party.save()
                return redirect(url_for('party_page.edit', id=party.id))
            else:
                error = 'Say yes if you want to cancel'
        return render_template('party/cancel.html', form=form, error=error, party=party)
    else:
        abort(404)

@party_page.route('/<id>', methods=['GET'])
def public(id):
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)

    if party:
        host = User.objects.filter(id=party.host).first()
        user = User.objects.filter(email=session.get('email')).first()
        return render_template('party/public.html', party=party, host=host, user=user)
    else:
        abort(404)

@party_page.route('/<id>/join', methods=['GET'])
@login_required
def join(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)    

    if user and party:
        if user not in party.attendees:
            party.attendees.append(user)
            party.save()
        return redirect(url_for('party_page.public',id=id))
    else:
        abort(404)

@party_page.route('/<id>/leave', methods=['GET'])
@login_required
def leave(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        party = Party.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)    

    if user and party:
        if user in party.attendees:
            party.attendees.remove(user)
            party.save()
        return redirect(url_for('party_page.public',id=id))
    else:
        abort(404)        

@party_page.route('/manage/<int:party_page_number>',methods=['GET'])
@party_page.route('/manage', methods=['GET'])
@login_required 
def manage(party_page_number=1):
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        parties = Party.objects.filter(host=user.id).order_by('-start_datetime').paginate(page=party_page_number, per_page=4)
        return render_template('party/manage.html', parties=parties)
    else:
        abort(404)

@party_page.route('/explore/<int:party_page_number>', methods=['GET'])
@party_page.route('/explore', methods=['GET'])
def explore(party_page_number=1):
    place = request.args.get('place')
    try:
        lng = float(request.args.get('lng'))
        lat = float(request.args.get('lat'))
        parties = Party.objects(location__near=[lng,lat], location__max_distance=10000,
                                 cancel=False).order_by('-start_datetime').paginate(page=party_page_number, per_page=4)
        return render_template('party/explore.html', parties=parties, place=place, lng=lng, lat=lat)
    except:
        return render_template('party/explore.html', place=place)

user/views.py
from flask import Blueprint,render_template,request,session,redirect,url_for,abort
import bcrypt 
import bson

from party.models import Party
from user.models import User
from user.forms import RegistrationForm,LoginForm,EditProfileForm,PasswordForm
from user.decorators import login_required 
from utilities.storage import upload_image_file

user_page = Blueprint('user_page',__name__)

@user_page.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm(request.form)
    error = None

    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data.encode('utf8'),user.password.encode('utf8')):
                session['email'] = user.email
                return redirect(request.args.get('next') or url_for('home'))
            else:
                user = None
        if not user:
            error = 'Your email or password was entered incorrectly'

    return render_template('user/login.html',form=form,error=error)
    #user = User(name='Raymond',password='123',email='email@gmail.com')
    #user.save()
    #return 'Hello {}! Your email address is {}'.format(user.name,user.email)
    #return "this is login page"

@user_page.route('/logout')
def logout():
    try:
        session.pop('email')
        return redirect(url_for('user_page.login'))
    except:
        return redirect(url_for('user_page.login'))


    
@user_page.route('/signup',methods=['GET','POST'])
def signup():
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data.encode('utf8'),salt)

        user = User(
            name=form.name.data,
            email=form.email.data.lower(),
            password=hashed_password
        )
        user.save()

        return redirect(url_for('user_page.login'))
    return render_template('user/signup.html',form=form)

@user_page.route('/edit',methods=['GET','POST'])
@login_required
def edit():
    user = User.objects.filter(email=session['email']).first()
    if user:
        error = None 
        message = None
        form = EditProfileForm(obj=user)

        if request.method =='POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email is already in use"
                else:
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'),'profile_image/',str(user.id))
                if image_url:
                    user.profile_image = image_url
                user.save()
                message = "Profile updated"
            
        return render_template('user/edit.html',user=user,form=form,error=error,message=message)
    else:
        abort(404)

@user_page.route('/password',methods=['GET','POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == "POST" and form.validate(): 
            if bcrypt.checkpw(form.old_password.data.encode('utf8'),user.password.encode('utf8')):
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data.encode('utf8'),salt)
                user.password = hashed_password.decode("utf-8")   # s.decode("utf-8") == str(s, 'utf-8') 
                # "password": "b'$2b$12$YtBDv2A/cRftPCE2gqh58e2TW0j3Otya1llxMpaefBhUab6BwVpzm'",  b'<hash>' is redundency. =b' ' 
                '''
                user = User(
                    password=hashed_password 
                )
                '''
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html',form=form,error=error,message=message)
    else:
        abort(404)

@user_page.route('/<id>/<int:party_page_number>', methods=['GET'])
@user_page.route('/<id>')
def profile(id, party_page_number=1):
    try:
        user = User.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user:
        parties = Party.objects(attendees__in=[user], cancel=False).order_by('-start_datetime').paginate(page=party_page_number, per_page=4)
        return render_template('user/profile.html',user=user, parties=parties)
    else:
        abort(404)

templates/party/cancel.html
{% extends "base.html" %}
{% block title %}Cancel a party{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>
            {{ party.name}}
        </h3>

        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('party_page.cancel', id=party.id) }}">

            {{ form.csrf_token }}
            {{ render_field(form.confirm, class="form-control")}}
            
            <button type="submit" class="btn btn-danger">
                Cancel Party
            </button>
            <a href="{{ url_for('party_page.edit', id=party.id) }}">back to edit party</a>
        </form>
    </div>
</div>
{% endblock %}

templates/party/create.html
{% extends "base.html" %}
{% block title %}Create Party{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="text-center">
            <h3>
                Create Party
            </h3>
        </div>
        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('party_page.create') }}" >

            {{ form.csrf_token }}
            {{ render_field(form.name, class="form-control") }}
            {{ render_field(form.gplace, class="form-control", id="autocomplete", placeholder="Enter your address") }}
            {{ render_field(form.place, class="form-control", id="place",readonly=true) }}
            {{ render_field(form.lng, class="form-control", id="lng", readonly=true) }}
            {{ render_field(form.lat, class="form-control", id="lat", readonly=true) }}
            {{ render_field(form.start_datetime, class="form-control", placeholder="e.g. YYYY-MM-DD HH:MM") }}
            {{ render_field(form.end_datetime, class="form-control", placeholder="e.g. YYYY-MM-DD HH:MM") }}
            {{ render_field(form.description, class="form-control", rows="8", minlength="50") }}

            <button type="submit" class="btn btn-success">
                Create Party
            </button>
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% include "googleapi.html" %}
{% endblock %}

templates/party/edit.html
{% extends "base.html" %}
{% block title %}Edit Party{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        {% if party.party_photo %}
        <img width="100%" src="{{ party.party_photo }}">
        {% else %}
        <img width="100%" src="{{ url_for('static', filename='img/party.png') }}">
        {% endif %}

        <div class="text-center">
            <h3>
                Edit Party
            </h3>
            <h6>
                <a href="{{ url_for('party_page.public', id=party.id) }}">Preview</a>
            </h6>
        </div>
        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}

        {% if message %}
        <div class="alert alert-success">
            {{ message }}
        </div>
        {% endif %}

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('party_page.edit', id=party.id) }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.name, class="form-control") }}
            {{ render_field(form.gplace, class="form-control",id="autocomplete", placeholder="Enter your address") }}
            {{ render_field(form.place, class="form-control", id="place",readonly=true) }}
            {{ render_field(form.lng, class="form-control", id="lng", readonly=true) }}
            {{ render_field(form.lat, class="form-control", id="lat", readonly=true) }}
            {{ render_field(form.start_datetime, class="form-control", placeholder="e.g. YYYY-MM-DD HH:MM") }}
            {{ render_field(form.end_datetime, class="form-control", placeholder="e.g. YYYY-MM-DD HH:MM") }}
            
            {{ render_field(form.photo, class="form-control") }}
            {{ render_field(form.description, class="form-control", rows="8", minlength="50") }}
            
            {% if party.cancel %}
            This party is canceled
            {% else %}
            <button type="submit" class="btn btn-success">
                Save
            </button>
            <a href="{{ url_for('party_page.cancel', id=party.id) }}">Cancel party</a>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% include "googleapi.html" %}
{% endblock %}

templates/party/explore.html
{% extends "base.html" %}
{% block title %}Explore{% endblock %}
{% block content %}

<div class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">
            Find a Party
        </h1>
        <p class="lead text-muted">
            If you want to go fast, go alone. If you want to go far, go together.
        </p>

        <form method='GET' action="{{ url_for('party_page.explore') }}">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for place...e.g.Potsdam NY" id="autocomplete">
                <input type="hidden" name="place" id="place">
                <input type="hidden" name="lng" id="lng">
                <input type="hidden" name="lat" id="lat">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="submit">
                        Go!
                    </button>
                </span>
            </div>
        </form>
    </div>
</div>

{% if parties and parties.pages > 0 %}
<p class="text-muted text-center">
    Party near {{ place }}
</p>


<div class="row">
    {% for party in parties.items %}
    <div class="col-md-6 party-item">
        <div class="card">
            <a href="{{ url_for('party_page.public', id=party.id) }}" target="_blank">
            {% if party.party_photo %}
            <img class="card-img-top party-photo-item" src="{{ party.party_photo}}">
            {% else %}
            <img class="card-img-top party-photo-item" src="{{ url_for('static', filename='img/party.png' )}}">
            {% endif %}
            </a>
            <div class="card-block">
                <h4 class="card-title">
                    {{ party.name }}
                </h4>
                <p class="card-text">
                    {{ party.description[:150] }}
                </p>
                <p class="card-text">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <a href="http://maps.google.com?q={{ party.place }}" target="_blank">
                    {{ party.place }}
                    </a>
                    <br>
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                    {{ party.start_datetime.strftime("%Y-%m-%d %I:%M%p") }}
                    <br>
                    <i class="fa fa-users" aria-hidden="true"></i>
                    {{ party.attendees|length }} attending
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row justify-content-center">
    <ul class="pagination">
        {% if parties.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('party_page.explore', party_page_number=parties.prev_num, place=place, lng=lng, lat=lat) }}">
                <span>&laquo;</span>
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link">
                Page {{ parties.page }} of {{ parties.pages }}
            </p>
        </li>
        {% if parties.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('party_page.explore', party_page_number=parties.next_num, place=place, lng=lng, lat=lat) }}">
                <span>&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</div>

{% elif place %}
<p class="text-muted text-center">
    We couldn't find any parties here :(
</p>
{% else %}
{% endif %}

{% endblock %}
{% block javascript %}
{% include "googleapi.html" %}
{% endblock %}

templates/party/manage.html
{% extends "base.html" %}
{% block title %}Manage Party{% endblock %}
{% block content %}

<h1>
    My Parties
</h1>

<div class="row">
    {% for party in parties.items %}
    <div class="col-md-6 party-item">
        <div class="card">
            {% if party.party_photo %}
            <img class="card-img-top party-photo-item" src="{{ party.party_photo}}">
            {% else %}
            <img class="card-img-top party-photo-item" src="{{ url_for('static', filename='img/party.png' )}}">
            {% endif %}
            <div class="card-block">
                <h4 class="card-title">
                    {{ party.name }}
                </h4>
                <p class="card-text">
                    {{ party.description[:150] }}
                </p>
                <p class="card-text">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <a href="http://maps.google.com?q={{ party.place }}" target="_blank">
                    {{ party.place }}
                    </a>
                    <br>
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                    {{ party.start_datetime.strftime("%Y-%m-%d %I:%M%p") }}
                    <br>
                    <i class="fa fa-users" aria-hidden="true"></i>
                    {{ party.attendees|length }} attending
                </p>
                {% if party.cancel %}
                <button class="btn btn-danger">
                    Canceled
                </button>
                {% else %}
                <a href="{{ url_for('party_page.edit', id=party.id) }}" class="btn btn-success">
                    Edit
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row justify-content-center">
    <ul class="pagination">
        {% if parties.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('party_page.manage', party_page_number=parties.prev_num) }}">
                <span>&laquo;</span>
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link">
                Page {{ parties.page }} of {{ parties.pages }}
            </p>
        </li>
        {% if parties.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('party_page.manage', party_page_number=parties.next_num) }}">
                <span>&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

templates/party/public.html
{% extends "base.html" %}
{% block title %}{{ party.name }}{% endblock %}
{% block content %}


<h3>
    {{ party.name }}
</h3>
<p class="text-muted">
    Hosted by
    <a href="{{ url_for('user_page.profile', id=party.host) }}">{{ host.name }}</a>
    {% if session.email == host.email %}
    <a href="{{ url_for('party_page.edit', id=party.id) }}">Edit</a>
    {% endif %}
</p>

<div class="row">
    <div class="col-md-8">
        {% if party.party_photo %}
        <img width="100%" src="{{ party.party_photo }}">
        {% else %}
        <img width="100%" src="{{ url_for('static', filename='img/party.png') }}">
        {% endif %}
    </div>

    <div class="col-md-4">
        <h6>
            Start Time
        </h6>
        <p>
            <i class="fa fa-clock-o" aria-hidden="true"></i>
            {{ party.start_datetime.strftime("%Y-%m-%d %I:%M%p") }}
        </p>
        <h6>
            End Time
        </h6>
        <p>
            <i class="fa fa-clock-o" aria-hidden="true"></i>
            {{ party.end_datetime.strftime("%Y-%m-%d %I:%M%p") }}
        </p>
        <h6>
            Place
        </h6>
        <p>
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            <a href="http://maps.google.com?q={{ party.place }}" target="_blank">
            {{ party.place }}
            </a>
        </p>

        {% if party.cancel %}
        This party has been canceled.
        {% elif session['email'] == host.email %}
        {% elif user in party.attendees %}
        <a href="{{ url_for('party_page.leave', id=party.id) }}" class="btn btn-danger">Leave</a>
        {% else %}
        <a href="{{ url_for('party_page.join', id=party.id) }}" class="btn btn-success">Join</a>
        {% endif %}

    </div>
</div>

<hr>
<h3>
    Description
</h3>
<div class="row">
    <div class="col-md-12">
        <p>
            {{ party.description }}
        </p>
    </div>
</div>

<hr>
<h3>
    Attendees
</h3>
<div class="row">
    {% for user in party.attendees %}
    <div class="col-md-3 text-center">
        <a href="{{ url_for('user_page.profile', id=user.id) }}">
        {% if user.profile_image %}
            <img width="150px" height="150px" src="{{ user.profile_image }}" 
                 class="img-thumbnail rounded-circle">
        {% else %}
            <img width="150px" height="150px" src="{{ url_for('static', filename='img/user.png') }}" 
                 class="img-thumbnail rounded-circle">
        {% endif %}
            <p>
                {{ user.name }}
            </p>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/party/testphoto.html
{% extends "base.html" %}
{% block title %}Test Photo{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <img width="100%" src="{{ url_for('static', filename='img/party.png') }}">

        <div class="text-center">
            <h3>
                Test Photo
            </h3>
        </div>

    </div>
</div>
{% endblock %}